name: ci-go-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  check-application:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      # (Opcional) Cache de módulos
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # (Opcional) Analise estática
      - name: Go vet
        run: go vet ./...

      - name: Run Go tests (all pkgs) with coverage
        run: go test ./... -coverprofile=coverage.out

      # (Opcional) Build do binário
      - name: Build app
        run: go build ./...

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # <— adicione esse secret
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out

      # Só precisa de QEMU se for multi-arch
      - name: Set up QEMU
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            greg0x46/ci-go:latest
            greg0x46/ci-go:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
