name: ci-go-workflow
on:
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    go-version: [1.25, 1.24]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Run Go tests
        run: go test

      - name: Run Go application
        run: go run math.go